# Side indstillinger
title: "Det Lille Køkken"
locale: "da-DK"
description: "Open Source Madviden"
url: "https://detlillekøkken.dk" 

# Tema indstillinger
remote_theme: "mmistakes/minimal-mistakes@4.24.4"
minimal_mistakes_skin: "default" # Jeg vil ændre farvetema senere (f.eks. 'air', 'contrast', 'mint')

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-recipe

# Gør det muligt at bruge detlillekøkken.dk korrekt
domain: "detlillekøkken.dk"

# Standard indstillinger for indlæg
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
