title: "Det Lille Køkken"
locale: "da-DK"
timezone: "Europe/Copenhagen"
words_per_minute: 200
description: "Min samling af opskrifter"
url: "https://detlillekøkken.dk"
baseurl: "" # Lad denne stå tom

# Tema indstillinger
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # Prøv 'air' eller 'mint' for et friskt køkken-look

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Side-opbygning
paginate: 5
paginate_path: /page:num/

# Standard indstillinger for opskrifter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
      read_time: true
      share: false
      comments: false

# footer:
#   links:
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/janushoi"
      
# author:
  name: "Janus"
  bio: "Madentusiast"
  avatar: "/assets/images/mig.jpg" # Du kan uploade et billede senere
  location: "Danmark"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/janushoi"

