title: "#DetLilleKøkken"
locale: "da-DK"
description: "Min samling af opskrifter"
url: "https://xn--detlillekkken-jnb.dk"

# Tema - Vi fjerner @4.24.4 for at undgå 404 fejlen
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Plugins - Vi holder os til dem, GitHub Pages officielt støtter i første omgang
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Standard indstillinger
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
